# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cpack.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63pack.proto\x12\x05\x63lass\"p\n\x0e\x43ontentPackDep\x12\x12\n\npackage_id\x18\x01 \x01(\t\x12\x17\n\x0fpackage_version\x18\x02 \x01(\t\x12\x14\n\x0cpackage_name\x18\x03 \x01(\t\x12\x1b\n\x13package_description\x18\x04 \x01(\t\"\x8d\x02\n\x0b\x43ontentPack\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x14\n\x0cproject_name\x18\x02 \x01(\t\x12\x17\n\x0fproject_version\x18\x03 \x01(\t\x12\x13\n\x0b\x61uthor_name\x18\x04 \x01(\t\x12\x10\n\x08synopsis\x18\x05 \x01(\t\x12\x11\n\thas_story\x18\x06 \x01(\x08\x12\x11\n\tread_only\x18\x08 \x01(\x08\x12\x15\n\rpreview_image\x18\t \x01(\t\x12\x1d\n\x15game_version_required\x18\n \x01(\x02\x12\x38\n\x19\x63ontent_pack_dependencies\x18\x14 \x03(\x0b\x32\x15.class.ContentPackDepb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cpack_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTENTPACKDEP._serialized_start=22
  _CONTENTPACKDEP._serialized_end=134
  _CONTENTPACK._serialized_start=137
  _CONTENTPACK._serialized_end=406
# @@protoc_insertion_point(module_scope)
