# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmusic.proto\x12\x05\x63lass\"*\n\nMusicGroup\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06tracks\x18\x02 \x03(\t\"-\n\x08MusicLib\x12!\n\x06groups\x18\x01 \x03(\x0b\x32\x11.class.MusicGroupb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MUSICGROUP._serialized_start=22
  _MUSICGROUP._serialized_end=64
  _MUSICLIB._serialized_start=66
  _MUSICLIB._serialized_end=111
# @@protoc_insertion_point(module_scope)
