---
name: GitHub Build Package
run-name: Build a ShadowRun ${{ github.ref }} content pack
on:
  - push
jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade polib protobuf
      - name: shiv in inapproriate image
        run: cp -v SR-Unlimited/ci-spawn.png SR-Unlimited/preview.png
      - name: Shiv in inappropriate stamp
        run: >
          sed "s|[0-9]{2}[a-kA-K][0-9]{2}|$(date +%Y-%m-%dT%H:%M)|" -i SR-Unlimited/data/items/Quest/Commlink.item.txt SR-Unlimited/data/stories/story.story.txt SR-Unlimited/project.cpack.txt
      - name: Build the package
        run: python phpexperiment/compiler.py -p ${{ github.ref_name }} SR-Unlimited
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 51f15c62336331d02c00440e-SR-Unlimited-${{ github.ref_name }}.cpz
          path: 51f15c62336331d02c00440e-SR-Unlimited.cpz
